version: '3'
services:
  web:
    build: .
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/database
    env_file:
      - .env.dev
  db:
    image: "postgres:12"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: