version: "3.7"
services:
  nginx:
    container_name: "nginx"
    image: nginx:alpine
    depends_on:
      - web
    ports:
      - "8082:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - custom

  web:
    container_name: "web"
    environment:
      - MONGODB_URL=mongodb://mongo_db/test_database
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom
    depends_on:
      - mongo_db

  mongo_db:
      image: mongo
      container_name: "mongo_db"
      ports:
        - "27017:27017"
      networks:
        - custom
      volumes:
        - ./data/db:/data/db

networks:
  custom:
    driver: bridge

volumes:
  db_data: