# Generated by Django 4.1.2 on 2022-12-29 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('vk_id', models.IntegerField(null=True)),
                ('telegram_id', models.IntegerField(null=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('last_updated_at', models.DateTimeField()),
                ('points', models.JSONField()),
                ('mark_formula', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.JSONField()),
                ('fine', models.FloatField()),
                ('mark', models.FloatField()),
                ('start_submit', models.DateTimeField()),
                ('last_updated_at', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hwhub.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hwhub.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('connect_code', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hwhub.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hwhub.studentgroup'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='students_groups',
            field=models.ManyToManyField(to='hwhub.studentgroup'),
        ),
    ]
